services:
  postgres-furnas-campanha:
    image: postgres:17-alpine
    container_name: postgres-furnas-campanha
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_FURNAS_USER}
      POSTGRES_PASSWORD: ${DB_FURNAS_PASSWORD}
      POSTGRES_DB: ${DB_FURNAS_NAME}
    ports:
      - "5433:5432"
    volumes:
      - furnas_campanha_data:/var/lib/postgresql/data
      - ./furnas-campanha/create-table.sql:/docker-entrypoint-initdb.d/1-create-table.sql
      - ./furnas-campanha/copy-table.sql:/docker-entrypoint-initdb.d/2-copy-table.sql
      - ./furnas-campanha/csv:/csv
    networks:
      - abp-network

  postgres-sima:
    image: postgres:17-alpine
    container_name: postgres-sima
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_SIMA_USER}
      POSTGRES_PASSWORD: ${DB_SIMA_PASSWORD}
      POSTGRES_DB: ${DB_SIMA_NAME}
    ports:
      - "5434:5432"
    volumes:
      - sima_data:/var/lib/postgresql/data
      - ./sima/create-table.sql:/docker-entrypoint-initdb.d/1-create-table.sql
      - ./sima/copy-table.sql:/docker-entrypoint-initdb.d/2-copy-table.sql
      - ./sima/csv:/csv
    networks:
      - abp-network

  postgres-balcar-campanha:
    image: postgres:17-alpine
    container_name: postgres-balcar-campanha
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_BALCAR_USER}
      POSTGRES_PASSWORD: ${DB_BALCAR_PASSWORD}
      POSTGRES_DB: ${DB_BALCAR_NAME}
    ports:
      - "5435:5432"
    volumes:
      - balcar_campanha_data:/var/lib/postgresql/data
      - ./balcar-campanha/create-table.sql:/docker-entrypoint-initdb.d/1-create-table.sql
      - ./balcar-campanha/copy-table.sql:/docker-entrypoint-initdb.d/2-copy-table.sql
      - ./balcar-campanha/csv:/csv
    networks:
      - abp-network

  server-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-app
    restart: always
    networks:
      - abp-network
    depends_on:
      - postgres-furnas-campanha
      - postgres-sima
      - postgres-balcar-campanha
    env_file:
      - ./.env
    volumes:
      - ./server:/usr/src/app
      - ./logs:/usr/src/app/logs
    command: npm run dev
    ports:
      - "3001:3000"

  front-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front-app
    restart: always
    networks:
      - abp-network
    env_file:
      - ./.env
    depends_on:
      - server-app
    environment:
      CHOKIDAR_USEPOLLING: "true"   # garante hot reload dentro do container
    volumes:
      - ./front:/usr/src/app        # código local
      - /usr/src/app/node_modules   # mantém dependências no container
    command: npm run dev -- --host
    ports:
      - "3002:5173"

volumes:
  furnas_campanha_data:
  sima_data:
  balcar_campanha_data:

networks:
  abp-network:
    driver: bridge
